/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ACER
 */
public class MainMenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuGUI
     */
    //my variables
    PhieuNhapGUI phieuNhap;
    PhieuXuatGUI phieuXuat;
    NhanVienGUI nhanVien;
    Account taiKhoan;
    BanHangGUI banHang;
    ThongKe thongKe;
    Warranty baoHanh;
    Permission_Manager phanQuyen;
<<<<<<< HEAD
    KhuVucKho1 khuVucKho;
=======
    
    ArrayList<JButton> buttonList;
    
>>>>>>> 70fb0ee0eb4c3c7658a6403ab1060a5b0644a6b1
    public MainMenuGUI() {
        initComponents();
        ImageIcon logo = new ImageIcon("src/img/logo.jpg");
        setIconImage(logo.getImage());
        
        //lấy tất cả button chức năng
        buttonList = getAllButtons(ChucNangPnl);
        for(JButton btn : buttonList) {
            function.HoverBtn(btn,buttonList);
        }
        
        //default
        banHang= new BanHangGUI();
        NoiDungPnl.add(banHang);
        NoiDungPnl.repaint();
        NoiDungPnl.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashBoard = new javax.swing.JPanel();
        TaiKhoanPnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ChucNangPnl = new javax.swing.JPanel();
        BanHangBtn = new javax.swing.JButton();
        SanPhamBtn = new javax.swing.JButton();
        KhachHangBtn = new javax.swing.JButton();
        PhieuXuatBtn = new javax.swing.JButton();
        KVKhoBtn = new javax.swing.JButton();
        PhieuNhapBtn = new javax.swing.JButton();
        TaiKhoanBtn = new javax.swing.JButton();
        NCCBtn = new javax.swing.JButton();
        NhanVienBtn = new javax.swing.JButton();
        BaoHanhBtn = new javax.swing.JButton();
        PhanQuyenBtn = new javax.swing.JButton();
        ThongKeBtn = new javax.swing.JButton();
        DangXuatBtn = new javax.swing.JButton();
        NoiDungPnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ CỬA HÀNG ĐIỆN THOẠI");
        setMinimumSize(new java.awt.Dimension(1000, 560));

        DashBoard.setBackground(new java.awt.Color(6, 66, 93));
        DashBoard.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DashBoard.setAlignmentX(0.0F);
        DashBoard.setAlignmentY(0.0F);

        TaiKhoanPnl.setBackground(new java.awt.Color(64, 103, 146));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
<<<<<<< HEAD
        jLabel2.setText("User Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
=======
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
>>>>>>> 70fb0ee0eb4c3c7658a6403ab1060a5b0644a6b1
        jLabel3.setText("Vị trí");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconUser.png"))); // NOI18N

        javax.swing.GroupLayout TaiKhoanPnlLayout = new javax.swing.GroupLayout(TaiKhoanPnl);
        TaiKhoanPnl.setLayout(TaiKhoanPnlLayout);
        TaiKhoanPnlLayout.setHorizontalGroup(
            TaiKhoanPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaiKhoanPnlLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(TaiKhoanPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        TaiKhoanPnlLayout.setVerticalGroup(
            TaiKhoanPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaiKhoanPnlLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ChucNangPnl.setOpaque(false);
        ChucNangPnl.setLayout(new java.awt.GridLayout(13, 10));

        BanHangBtn.setBackground(new java.awt.Color(6, 66, 93));
        BanHangBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BanHangBtn.setForeground(new java.awt.Color(255, 255, 255));
        BanHangBtn.setText("Bán Hàng");
        BanHangBtn.setBorder(null);
        BanHangBtn.setFocusPainted(false);
        BanHangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BanHangBtnActionPerformed(evt);
            }
        });
        ChucNangPnl.add(BanHangBtn);

        SanPhamBtn.setBackground(new java.awt.Color(6, 66, 93));
        SanPhamBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SanPhamBtn.setForeground(new java.awt.Color(255, 255, 255));
        SanPhamBtn.setText("Sản Phẩm");
        SanPhamBtn.setBorder(null);
        SanPhamBtn.setFocusPainted(false);
        ChucNangPnl.add(SanPhamBtn);

        KhachHangBtn.setBackground(new java.awt.Color(6, 66, 93));
        KhachHangBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        KhachHangBtn.setForeground(new java.awt.Color(255, 255, 255));
        KhachHangBtn.setText("Khách Hàng");
        KhachHangBtn.setBorder(null);
        KhachHangBtn.setFocusPainted(false);
        ChucNangPnl.add(KhachHangBtn);

        PhieuXuatBtn.setBackground(new java.awt.Color(6, 66, 93));
        PhieuXuatBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PhieuXuatBtn.setForeground(new java.awt.Color(255, 255, 255));
        PhieuXuatBtn.setText("Phiếu Xuất");
        PhieuXuatBtn.setBorder(null);
        PhieuXuatBtn.setFocusPainted(false);
        PhieuXuatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhieuXuatBtnActionPerformed(evt);
            }
        });
        ChucNangPnl.add(PhieuXuatBtn);

<<<<<<< HEAD
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setText("Khu Vực Kho");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
=======
        KVKhoBtn.setBackground(new java.awt.Color(6, 66, 93));
        KVKhoBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        KVKhoBtn.setForeground(new java.awt.Color(255, 255, 255));
        KVKhoBtn.setText("Khu Vực Kho");
        KVKhoBtn.setBorder(null);
        KVKhoBtn.setFocusPainted(false);
        ChucNangPnl.add(KVKhoBtn);
>>>>>>> 70fb0ee0eb4c3c7658a6403ab1060a5b0644a6b1

        PhieuNhapBtn.setBackground(new java.awt.Color(6, 66, 93));
        PhieuNhapBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PhieuNhapBtn.setForeground(new java.awt.Color(255, 255, 255));
        PhieuNhapBtn.setText("Phiếu Nhập");
        PhieuNhapBtn.setBorder(null);
        PhieuNhapBtn.setFocusPainted(false);
        PhieuNhapBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhieuNhapBtnMouseClicked(evt);
            }
        });
        PhieuNhapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhieuNhapBtnActionPerformed(evt);
            }
        });
        ChucNangPnl.add(PhieuNhapBtn);

        TaiKhoanBtn.setBackground(new java.awt.Color(6, 66, 93));
        TaiKhoanBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TaiKhoanBtn.setForeground(new java.awt.Color(255, 255, 255));
        TaiKhoanBtn.setText("Tài Khoản");
        TaiKhoanBtn.setBorder(null);
        TaiKhoanBtn.setFocusPainted(false);
        TaiKhoanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaiKhoanBtnActionPerformed(evt);
            }
        });
        ChucNangPnl.add(TaiKhoanBtn);

        NCCBtn.setBackground(new java.awt.Color(6, 66, 93));
        NCCBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NCCBtn.setForeground(new java.awt.Color(255, 255, 255));
        NCCBtn.setText("Nhà Cung Cấp");
        NCCBtn.setBorder(null);
        NCCBtn.setFocusPainted(false);
        ChucNangPnl.add(NCCBtn);

        NhanVienBtn.setBackground(new java.awt.Color(6, 66, 93));
        NhanVienBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NhanVienBtn.setForeground(new java.awt.Color(255, 255, 255));
        NhanVienBtn.setText("Nhân Viên");
        NhanVienBtn.setBorder(null);
        NhanVienBtn.setFocusPainted(false);
        NhanVienBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhanVienBtnActionPerformed(evt);
            }
        });
        ChucNangPnl.add(NhanVienBtn);

        BaoHanhBtn.setBackground(new java.awt.Color(6, 66, 93));
        BaoHanhBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BaoHanhBtn.setForeground(new java.awt.Color(255, 255, 255));
        BaoHanhBtn.setText("Bảo Hành");
        BaoHanhBtn.setBorder(null);
        BaoHanhBtn.setFocusPainted(false);
        BaoHanhBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaoHanhBtnActionPerformed(evt);
            }
        });
        ChucNangPnl.add(BaoHanhBtn);

        PhanQuyenBtn.setBackground(new java.awt.Color(6, 66, 93));
        PhanQuyenBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PhanQuyenBtn.setForeground(new java.awt.Color(255, 255, 255));
        PhanQuyenBtn.setText("Phân Quyền");
        PhanQuyenBtn.setBorder(null);
        PhanQuyenBtn.setFocusPainted(false);
        PhanQuyenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhanQuyenBtnActionPerformed(evt);
            }
        });
        ChucNangPnl.add(PhanQuyenBtn);

        ThongKeBtn.setBackground(new java.awt.Color(6, 66, 93));
        ThongKeBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ThongKeBtn.setForeground(new java.awt.Color(255, 255, 255));
        ThongKeBtn.setText("Thống Kê");
        ThongKeBtn.setBorder(null);
        ThongKeBtn.setFocusPainted(false);
        ThongKeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongKeBtnActionPerformed(evt);
            }
        });
        ChucNangPnl.add(ThongKeBtn);

        DangXuatBtn.setBackground(new java.awt.Color(6, 66, 93));
        DangXuatBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DangXuatBtn.setForeground(new java.awt.Color(255, 51, 51));
        DangXuatBtn.setText("Đăng Xuất");
        DangXuatBtn.setBorder(null);
        DangXuatBtn.setFocusPainted(false);
        DangXuatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangXuatBtnActionPerformed(evt);
            }
        });
        ChucNangPnl.add(DangXuatBtn);

        javax.swing.GroupLayout DashBoardLayout = new javax.swing.GroupLayout(DashBoard);
        DashBoard.setLayout(DashBoardLayout);
        DashBoardLayout.setHorizontalGroup(
            DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaiKhoanPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChucNangPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        DashBoardLayout.setVerticalGroup(
            DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardLayout.createSequentialGroup()
                .addComponent(TaiKhoanPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ChucNangPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        getContentPane().add(DashBoard, java.awt.BorderLayout.LINE_START);

        NoiDungPnl.setBackground(new java.awt.Color(255, 255, 255));
        NoiDungPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NoiDungPnl.setPreferredSize(new java.awt.Dimension(1200, 725));
        NoiDungPnl.setLayout(new java.awt.BorderLayout());
        getContentPane().add(NoiDungPnl, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static ArrayList<JButton> getAllButtons(JPanel panel) {
        ArrayList<JButton> buttonList = new ArrayList<>();
        Component[] components = panel.getComponents();

        for (Component component : components) {
            if (component instanceof javax.swing.JButton) {
                buttonList.add((JButton) component);
            }
        }
        return buttonList;
    }
    
    private void DangXuatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangXuatBtnActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn thoát?")==0) {
            this.dispose();
            new LogInGUI().setVisible(true);
        }
    }//GEN-LAST:event_DangXuatBtnActionPerformed

    private void ThongKeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongKeBtnActionPerformed
        // TODO add your handling code here:
        NoiDungPnl.removeAll();
        thongKe= new ThongKe();
        NoiDungPnl.add(thongKe);
        NoiDungPnl.repaint();
        NoiDungPnl.validate();
    }//GEN-LAST:event_ThongKeBtnActionPerformed

    private void PhanQuyenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhanQuyenBtnActionPerformed
        // TODO add your handling code here:
        NoiDungPnl.removeAll();
        phanQuyen= new Permission_Manager();
        NoiDungPnl.add(phanQuyen);
        NoiDungPnl.repaint();
        NoiDungPnl.validate();
    }//GEN-LAST:event_PhanQuyenBtnActionPerformed

    private void BaoHanhBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaoHanhBtnActionPerformed
        // TODO add your handling code here:
        NoiDungPnl.removeAll();
        baoHanh= new Warranty();
        NoiDungPnl.add(baoHanh);
        NoiDungPnl.repaint();
        NoiDungPnl.validate();
    }//GEN-LAST:event_BaoHanhBtnActionPerformed

    private void NhanVienBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhanVienBtnActionPerformed
        NoiDungPnl.removeAll();
        nhanVien=new NhanVienGUI();
        NoiDungPnl.add(nhanVien,BorderLayout.CENTER);
        NoiDungPnl.repaint();
        NoiDungPnl.validate();
    }//GEN-LAST:event_NhanVienBtnActionPerformed

    private void TaiKhoanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaiKhoanBtnActionPerformed
        // TODO add your handling code here:
        NoiDungPnl.removeAll();
        taiKhoan= new Account();
        NoiDungPnl.add(taiKhoan);
        NoiDungPnl.repaint();
        NoiDungPnl.validate();
    }//GEN-LAST:event_TaiKhoanBtnActionPerformed

    private void PhieuNhapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhieuNhapBtnActionPerformed
        // TODO add your handling code here:
        NoiDungPnl.removeAll();
        phieuNhap=new PhieuNhapGUI();
        NoiDungPnl.add(phieuNhap,BorderLayout.CENTER);
        NoiDungPnl.revalidate();
    }//GEN-LAST:event_PhieuNhapBtnActionPerformed

    private void PhieuNhapBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhieuNhapBtnMouseClicked

    }//GEN-LAST:event_PhieuNhapBtnMouseClicked

    private void PhieuXuatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhieuXuatBtnActionPerformed
        // TODO add your handling code here:
        NoiDungPnl.removeAll();
        phieuXuat=new PhieuXuatGUI();
        NoiDungPnl.add(phieuXuat,BorderLayout.CENTER);
        NoiDungPnl.repaint();
        NoiDungPnl.revalidate();
    }//GEN-LAST:event_PhieuXuatBtnActionPerformed

    private void BanHangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BanHangBtnActionPerformed
        NoiDungPnl.removeAll();
        banHang= new BanHangGUI();
        NoiDungPnl.add(banHang);
        NoiDungPnl.repaint();
        NoiDungPnl.validate();
    }//GEN-LAST:event_BanHangBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        viewContent.removeAll();
        khuVucKho = new KhuVucKho1();
        viewContent.add(khuVucKho);
        viewContent.repaint();
        viewContent.validate();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatFlat Dark".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BanHangBtn;
    private javax.swing.JButton BaoHanhBtn;
    private javax.swing.JPanel ChucNangPnl;
    private javax.swing.JButton DangXuatBtn;
    private javax.swing.JPanel DashBoard;
    private javax.swing.JButton KVKhoBtn;
    private javax.swing.JButton KhachHangBtn;
    private javax.swing.JButton NCCBtn;
    private javax.swing.JButton NhanVienBtn;
    private javax.swing.JPanel NoiDungPnl;
    private javax.swing.JButton PhanQuyenBtn;
    private javax.swing.JButton PhieuNhapBtn;
    private javax.swing.JButton PhieuXuatBtn;
    private javax.swing.JButton SanPhamBtn;
    private javax.swing.JButton TaiKhoanBtn;
    private javax.swing.JPanel TaiKhoanPnl;
    private javax.swing.JButton ThongKeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
