/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.List;
import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

import com.formdev.flatlaf.ui.FlatListCellBorder.Default;

import BUS.PermissionManagerBUS;
import DTO.PermissionManagerDTO;
import GUI.Dialog.Permission_ManagerDialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Danny
 */
public class Permission_Manager extends javax.swing.JPanel {
    public PermissionManagerBUS perBUS = new PermissionManagerBUS();
    public ArrayList<PermissionManagerDTO> list = perBUS.getAll();
    public PermissionManagerDTO perDTO;

    
    public Permission_Manager() {
        initComponents();
        eventPermission();
        loadData(list);
    }
  
   
    public void loadData(ArrayList<PermissionManagerDTO> list) {
        DefaultTableModel tblModel = (DefaultTableModel) List_Permission.getModel();
        while (tblModel.getRowCount() > 0) {
            tblModel.removeRow(0);
            
        }

        for (PermissionManagerDTO per : list) {
            tblModel.addRow(new Object[] {
                per.getMaNhomQuyen(),
                per.getTenNhomQuyen()
            });
        }
        
        List_Permission.setModel(tblModel);
        List_Permission.repaint();
        List_Permission.validate();
    }
    public void eventPermission(){
        toolBar.getAddBtn().addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
               Permission_ManagerDialog a= new Permission_ManagerDialog("Thêm nhân viên","add"); 
             }
        });
        toolBar.getEditBtn().addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                if(getRowIndex()>=0){
                Permission_ManagerDialog a= new Permission_ManagerDialog("Update nhân viên","update",list.get(getRowIndex())); 
                }
                else{
                           JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng có trong bảng!");
               
                }
             }
            
        });
    }
    public int getRowIndex(){
        int row=List_Permission.getSelectedRow();
        return row;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        List_Permission = new javax.swing.JTable();
        toolBar = new GUI.toolBar();

        setPreferredSize(new java.awt.Dimension(1200, 725));

        List_Permission.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Nhóm Quyền", "Tên Đăng Nhập"
            }
        ));
        List_Permission.setRequestFocusEnabled(false);
        List_Permission.setShowGrid(true);
        jScrollPane1.setViewportView(List_Permission);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable List_Permission;
    private javax.swing.JScrollPane jScrollPane1;
    protected GUI.toolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
