/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.PhieuNhapBUS;
import DTO.NhanVienDTO;
import DTO.NhaCungCapDTO;
import java.awt.event.ActionEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;
/**
 *
 * @author ACER
 */
public class PhieuNhapGUI extends javax.swing.JPanel {

    /**
     * Creates new form PhieuNhapGUI
     */
    public PhieuNhapGUI() {
        initComponents();
        
        BUS.PhieuNhapBUS.pouringData(tblDSPN);
        
        toolBar.getCbbFilter().removeAllItems();
        toolBar.getCbbFilter().setModel(new DefaultComboBoxModel(new String [] {
            "Tất cả","Mã phiếu nhập","Tên nhà cung cấp","Tên nhân viên"
        }));
        
        cbbNCC.setModel(new DefaultComboBoxModel<>(getNameNCC()));
        cbbNVN.setModel(new DefaultComboBoxModel<>(getNameNV()));
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        TableColumnModel columnModel = tblDSPN.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(1);
        columnModel.getColumn(0).setCellRenderer(centerRenderer);
        columnModel.getColumn(1).setPreferredWidth(1);
        columnModel.getColumn(1).setCellRenderer(centerRenderer);
        
        
        toolBar.getFindBtn().addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(function.TextFieldIsEmpty(toolBar.getTfSearch(), "nội dung tìm kiếm","Nhập nội dung tìm kiếm...")) {
                    return;
                }
                PhieuNhapBUS.pouringData(tblDSPN, PhieuNhapBUS.search(toolBar.getCbbFilter().getSelectedIndex(), toolBar.getTfSearch().getText().strip()));
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rowConfig = new javax.swing.JPopupMenu();
        edit = new javax.swing.JMenuItem();
        remove = new javax.swing.JMenuItem();
        details = new javax.swing.JMenuItem();
        toolBar = new GUI.toolBar();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSPN = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelNCC = new javax.swing.JLabel();
        cbbNCC = new javax.swing.JComboBox<>();
        labelNV = new javax.swing.JLabel();
        cbbNVN = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jSlider1 = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jSlider2 = new javax.swing.JSlider();
        detroyFilterBtn = new javax.swing.JButton();

        edit.setText("Sửa");
        rowConfig.add(edit);

        remove.setText("Xóa");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        rowConfig.add(remove);

        details.setText("Details");
        rowConfig.add(details);

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1200, 725));
        setLayout(new java.awt.BorderLayout());
        add(toolBar, java.awt.BorderLayout.PAGE_START);

        jPanel3.setOpaque(false);

        tblDSPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã phiếu", "Nhà cung cấp", "Nhân viên", "Thời gian", "Tổng tiền (VNĐ)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSPN.setComponentPopupMenu(rowConfig);
        tblDSPN.setOpaque(false);
        tblDSPN.setShowGrid(true);
        jScrollPane1.setViewportView(tblDSPN);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.setMinimumSize(new java.awt.Dimension(140, 524));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(140, 675));
        jPanel2.setLayout(new java.awt.GridLayout(20, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bộ lọc");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1);

        labelNCC.setText("Nhà cung cấp");
        jPanel2.add(labelNCC);

        jPanel2.add(cbbNCC);

        labelNV.setText("Nhân viên nhập");
        jPanel2.add(labelNV);

        jPanel2.add(cbbNVN);

        jLabel3.setText("Từ ngày");
        jPanel2.add(jLabel3);
        jPanel2.add(jDateChooser1);

        jLabel4.setText("Đến ngày");
        jPanel2.add(jLabel4);
        jPanel2.add(jDateChooser2);

        jLabel5.setText("Từ số tiền (VNĐ)");
        jPanel2.add(jLabel5);
        jPanel2.add(jTextField4);

        jSlider1.setValue(0);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jPanel2.add(jSlider1);

        jLabel6.setText("Đến số tiền (VNĐ)");
        jPanel2.add(jLabel6);
        jPanel2.add(jTextField5);

        jSlider2.setValue(0);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        jPanel2.add(jSlider2);

        detroyFilterBtn.setBackground(java.awt.Color.red);
        detroyFilterBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        detroyFilterBtn.setForeground(new java.awt.Color(5, 7, 15));
        detroyFilterBtn.setText("Hủy Bộ Lọc");
        detroyFilterBtn.setPreferredSize(new java.awt.Dimension(95, 40));
        jPanel2.add(detroyFilterBtn);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel4, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        try {
            DecimalFormat decimalFormat = new DecimalFormat("#,###");
            jTextField4.setText(decimalFormat.format(1000000000*((double)jSlider1.getValue()/100)));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
        // TODO add your handling code here:
        try {
            DecimalFormat decimalFormat = new DecimalFormat("#,###");
            jTextField5.setText(decimalFormat.format(1000000000*((double)jSlider2.getValue()/100)));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jSlider2StateChanged

    public static String[] getNameNCC() {
        ArrayList<NhaCungCapDTO> myArr = new DAO.NhaCungCapDAO().selecAll();
        String[] s = new String[myArr.size()+1];
        int i = 1;
        s[0] = "";
        for(NhaCungCapDTO x : myArr) {
            s[i]=x.getTenNCC();
            i++;
        }
        return s;
    }
    public static String[] getNameNV() {
        ArrayList<NhanVienDTO> myArr = new DAO.NhanVienDAO().selecAll();
        String[] s = new String[myArr.size()+1];
        int i = 1;
        s[0] = "";
        for(NhanVienDTO x : myArr) {
            s[i]=x.getHoTen();
            i++;
        }
        return s;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JComboBox<String> cbbNCC;
    protected javax.swing.JComboBox<String> cbbNVN;
    private javax.swing.JMenuItem details;
    private javax.swing.JButton detroyFilterBtn;
    private javax.swing.JMenuItem edit;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    protected javax.swing.JLabel labelNCC;
    protected javax.swing.JLabel labelNV;
    private javax.swing.JMenuItem remove;
    private javax.swing.JPopupMenu rowConfig;
    protected javax.swing.JTable tblDSPN;
    protected GUI.toolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
