/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import DTO.KhachHangDTO;
import DTO.NhanVienDTO;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author ACER
 */
public class PhieuXuatGUI extends PhieuNhapGUI {

    /**
     * Creates new form PhieuXuat
     */
    public PhieuXuatGUI() {
        super();
        labelNCC.setText("Khách hàng");
        labelNV.setText("Nhân viên xuất");
        tblDSPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã phiếu", "Khách hàng", "Nhân viên", "Thời gian", "Tổng tiền (VNĐ)"
            }));
        BUS.PhieuXuatBUS.pouringData(tblDSPN);
        
        
        toolBar.getCbbFilter().removeAllItems();
        toolBar.getCbbFilter().setModel(new DefaultComboBoxModel(new String [] {
            "Tất cả","Mã phiếu","Tên khách hàng","Tên nhân viên"
        }));
        
        cbbNCC.setModel(new DefaultComboBoxModel<>(getTenKH()));
        cbbNVN.setModel(new DefaultComboBoxModel<>(getTenNV()));
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        TableColumnModel columnModel = tblDSPN.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(0).setCellRenderer(centerRenderer);
        columnModel.getColumn(1).setPreferredWidth(100);
        columnModel.getColumn(1).setCellRenderer(centerRenderer);
        columnModel.getColumn(2).setPreferredWidth(400);
        columnModel.getColumn(3).setPreferredWidth(200);
        columnModel.getColumn(4).setPreferredWidth(200);
        columnModel.getColumn(5).setPreferredWidth(200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 963, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public static String[] getTenKH() {
        ArrayList<KhachHangDTO> myArr = new DAO.KhachHangDAO().selecAll();
        String[] s = new String[myArr.size()+1];
        int i = 1;
        s[0] = "";
        for(KhachHangDTO x : myArr) {
            s[i]=x.getTenKhachHang();
            i++;
        }
        return s;
    }
    public static String[] getTenNV() {
        ArrayList<NhanVienDTO> myArr = new DAO.NhanVienDAO().selecAll();
        String[] s = new String[myArr.size()+1];
        int i = 1;
        s[0] = "";
        for(NhanVienDTO x : myArr) {
            s[i]=x.getHoTen();
            i++;
        }
        return s;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
